export type AsyncStorageEntries =
  | "language"
  | "theme"
  | "initialHomescreen"
  | "cafeteria"
  | "course"
  | "icalUrl"
  | "accessGranted"
  | "dhbwLocation"
  | "notifications-allowed"
  | "notifications-settings"
  | "restaurantScreen.alreadySeen"
  | "lectures"
  | "nextStoreReviewRequestTime"
  | "lecture-badge-count"
  | "lecture-notification-cache"
  | "restaurant-idx";
