export type AsyncStorageEntries =
  | "language"
  | "theme"
  | "initialHomescreen"
  | "cafeteria"
  | "course"
  | "icalUrl"
  | "accessGranted"
  | "dhbwLocation"
  | "notifications-allowed"
  | "notifications-settings"
  | "restaurantScreen.alreadySeen"
  | "restaurantScreen.timesVisit"
  | "lectures"
  | "nextStoreReviewRequest";
